[project]
name = "mcp-bothost"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "mcp>=1.7.1",
    "openai-agents>=0.0.14",
    "python-dotenv>=1.1.0",
]
